security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
#        in_memory: { memory: ~ }
        in_database:
            entity:
                class: App\Entity\User
                property: username

    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 7

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            anonymous: true

        main:

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                username_parameter: username
                password_parameter: password

            logout: ~

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/login_check, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/job/delete, roles: ROLE_ADMIN }
         - { path: ^/job/edit, roles: ROLE_ADMIN }
         - { path: ^/worker/(create|delete), roles: ROLE_ADMIN }
 #        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED } #catch all
#         - { path: ^/profile, roles: ROLE_USER }
